name: Test

on:
  push:
    branches: [main]

jobs:
  test_action:
    name: Test Action
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        elvish-version: [0.20.1, HEAD]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: elves/setup-elvish@main
      with:
        elvish-version: ${{ matrix.elvish-version }}
    - name: Run with Elvish
      shell: elvish {0}
      run: |
        echo This is Elvish $version
        elvish -c 'echo Can be used as an external command too'
        elvish-${{ matrix.elvish-version }} -c 'echo Also available with explicit version'
